language: php

sudo: false

addons:
  apt:
    packages: libssh2-1-dev

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install: composer self-update

install:
  - pecl install ssh2-beta < ./tests/.non-interactive
  - composer install

before_script: mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
